trigger:
  branches:
    include:
      - development
      - master
  paths:
    exclude:
      - "pipelines/*.yml"
      - "docs/*"
      - "config/*"
      - "license/*"
      - "*.azcli"

pool:
  vmImage: ubuntu-latest

parameters:
  - name: azureServicePrincipal
    displayName: Azure Service Principal
    type: string
    default:  pan-firewall-dev-lab

variables:
- group: firewall-vars-1                                # Group variables
                                                        #   deployFirwall
                                                        #   environment
                                                        #   location
                                                        #   parameterFile
                                                        #   subnetPrefix
                                                        #   templateFile
                                                        # Pipeline variables
                                                        #   adminPassword
                                                        #   bootstrapAccessKey
                                                        #   licenseApiKeyValue
- name: varResourceGroupName
  value: sfc-$(subnetPrefix)-$(environment)-rg

stages:
- stage: prerequisites
  jobs:
    - job: createResourceGroup
      displayName: Create the Resource Group
      steps:
        - task: AzureCLI@2
          inputs:
            connectedServiceNameARM: ${{ parameters.azureServicePrincipal }}
            scriptType:  bash
            scriptLocation: inlineScript
            inlineScript:  az group create -l $(location) -n $(varResourceGroupName) --tags Application=network Team=networking Department=it Environment=$(environment)
            failOnStandardError:  true
    - job: acceptTerms
      dependsOn: createResourceGroup
      steps:
      - task: AzureCLI@2
        inputs:
          connectedServiceNameARM: ${{ parameters.azureServicePrincipal }}
          scriptType:  bash
          scriptLocation: inlineScript
          inlineScript:  az vm image terms accept --urn paloaltonetworks:vmseries-flex:byol:10.1.6
          failOnStandardError: true

#- stage: validate
#  jobs:
#    - job: testResourceGroup
#      steps:
#        - task: AzureCLI@2
#          inputs:
#            connectedServiceNameARM: ${{ parameters.azureServicePrincipal }}
#            scriptType:  bash
#            scriptLocation: inlineScript
#            inlineScript: az group exists -n sfc-network-dev-rg- # test failure
#            failOnStandardError:  true

- stage: createFirewall
  jobs:
    - job: test_variables
      steps:
        - bash: |
            echo 'bootstrapAccessKey = '$(bootstrapAccessKey)
            echo 'deployFirewall = '$(deployFirewall)
            echo 'environment = '$(environment)
            echo 'location = '$(location)
            echo 'parameterFile = '$(parameterFile)
            echo 'subnetPrefix = '$(subnetPrefix)
            echo 'templateFile = '$(templateFile)
            echo 'varResourceGroupName = '$(varResourceGroupName)
            echo 'pwd'
            pwd
            echo 'ls -l'
            ls -l

    - job: deployTemplate
      steps:
        - bash: echo 'Deploying the firewall'
        - task: AzureResourceManagerTemplateDeployment@3
          inputs:
            deploymentScope: Resource Group
            azureResourceManagerConnection: ${{ parameters.azureServicePrincipal }}
            action: Create Or Update Resource Group
            resourceGroupName: $(varResourceGroupName)
            location: $(location)
            templateLocation: Linked artifact
            csmFile: $(templateFile)
            csmParametersFile: $(parameterFile)
            overrideParameters: -adminPassword $(adminPassword) -bootstrapAccessKey $(bootstrapAccessKey)
            deploymentMode: Incremental

    - job: wait
      pool: server
      dependsOn: deployTemplate
      steps:
        - task: Delay@1
          displayName: Wait for the Firewall deployment to complete
          inputs:
            delayForMinutes: '15'
