name: armTemplateDeployment

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  push:
    branches:
      - master
      - main_rework
  workflow_dispatch:

env:
  location: westus3
  subscriptionID: 6081cfb9-7cb9-4b84-8be8-337fdcac59f6

jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIAL_VS_SANDBOX }}

      - name: deploy-resource-group-template
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionID: ${{ env.subscription_id}}
          region: ${{ env.location}}
          template: ./rg.json
          parameters: ./rg.parameters.json
          deploymentName: resourcegroup

