name: armTemplateDeployment

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  push:
    branches:
      - master
      - '*devel'
      - firewall
  workflow_dispatch:

env:
  location: westus3
  subscriptionID: 6081cfb9-7cb9-4b84-8be8-337fdcac59f6
  networkResourceGroup: sfc-network-dev-rg_
  resourceGroupName:  sfc-firewall-dev-rg_

jobs:
  DeployResourceGroup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIAL_VS_SANDBOX }}

      - uses: Azure/CLI@v1
        with:
          inlineScript: |
            #!/bin/bash
            # set account
            az account set -s 'vs_sandbox'
            az group create -n ${{ env.resourceGroupName }} -l ${{ env.location }}
            az group create -n ${{ env.networkResourceGroup }} -l ${{ env.location }}
            echo "Azure resource groups created"

  armDeployMainTemplate:
    runs-on:  ubuntu-latest
    needs:  DeployResourceGroup
    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIAL_VS_SANDBOX }}

      - name: deploy-main-template
        uses: Azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName:  ${{ env.resourceGroupName }}
          subscriptionID: ${{ env.subscription_id}}
          region: ${{ env.location}}
          template: ./main.json
          parameters: ./main.parameters.json
          deploymentName: main
